version: '3.8'

services:
  api:
    image: onlynebrasil-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - MYSQL_HOST=193.203.175.122
      - MYSQL_USER=u389104733_root
      - MYSQL_PASSWORD=15324948@Yu
      - MYSQL_DB=u389104733_shoplink
      - PORT=3000
    depends_on:
      - mysql

  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 15324948@Yu
      MYSQL_DATABASE: u389104733_shoplink
      MYSQL_USER: u389104733_root
      MYSQL_PASSWORD: 15324948@Yu
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
